---
title: "Assignment 4 Rmarkdown"
author: "Nelson Gould, Max Russer, Caio Vianna"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
# Install packages and read in csv files

library(tidyverse)
library(knitr)
library(kableExtra)
library(plotly)
library(extrafont)
library(effsize)
library(vcdExtra)
library(car)
library(ggsignif)
library(stargazer)

grad_enroll <- read_csv("grad_enroll_simplified.csv")
doc_salary <- read_csv("median_doctoral_salary.csv")
faculty_salary <- read_csv("faculty_salary_data.csv")
phd_field <- read_csv("phd_by_field_simplified.csv")

```


```{r}

# 1. Male and female graduate enrollment (1967 - 2015).

male_female_grad_graph <- ggplot(grad_enroll, aes(x = Year)) +
  geom_point(aes(y = total_males/1000), color = "skyblue", alpha = 0.75) +
  geom_point(aes(y = total_females/1000), color = "tomato", alpha = 0.75) +
  theme_classic() +
  labs(y = "Graduate Enrollment Count (1000 students)") +
  geom_smooth(aes(y = total_males/1000), method = lm, se = TRUE, size = 0.5, color = "skyblue", fill = "skyblue",alpha = 0.25) +
  geom_smooth(aes(y = total_females/1000), method = lm, se = TRUE, size = 0.5, color = "tomato", fill = "tomato",alpha = 0.25) +
  scale_x_continuous(expand = c(0,0),limits = c(1966,2016)) +
  scale_y_continuous(expand = c(0,0),limits = c(250,1800))
  
male_female_grad_graph

# Trend analysis
# Male

male_grad_enroll_model <- lm(total_males/1000 ~ Year, data = grad_enroll)
summary(male_grad_enroll_model)

cor.test(grad_enroll$Year, grad_enroll$total_males/1000)

# Female
female_grad_enroll_model <- lm(total_females/1000 ~ Year, data = grad_enroll)
summary(female_grad_enroll_model)

cor.test(grad_enroll$Year, grad_enroll$total_females/1000)

# total_males = 9.069(Year) - 17112.153, p < 2.2x10^-16 -- R^2 = 0.8545 -- F(1,47) = 276, -- R = 0.9243

# total_females = 30.13(Year) - 58955.50 -- R^2 = 0.9827 -- F(1,47) = 2669, p < 2.2x10^-16 -- R = 0.9913

plot(male_grad_enroll_model)
plot(female_grad_enroll_model)

```
Figure 1. 

```{r}

# 2. Shifts in female PhD recipients by field (1985, 2000, and 2015).

# Make proportion graph? 
# Allison basically said to make proportion table in word. 

phd_tble <- phd_field %>%
  filter(field_of_study != "NA") %>%
  filter(field_of_study != "Female") %>% 
  select(field_of_study, number_1985, number_2000, number_2015) %>% 
  select(-field_of_study)

colnames(phd_tble) <- c("1985", "2000", "2015")
rownames(phd_tble) <- c("Physical & Earth Sciences", "Engineering", "Education", "Humanities & Arts")

phd_tble
mat_phd_tble <- as.matrix(phd_tble)
noprop_phd_x2 <- chisq.test(mat_phd_tble)
noprop_phd_x2

phd_prop <- prop.table(as.matrix(phd_tble), 2)


phd_x2 <- chisq.test(phd_tble)

phd_x2

phd_prop_rnd <- phd_prop %>%
  round(2)

phd_prop_tble <- kable(phd_prop_rnd, col.names = c("1985", "2000", "2015")) %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>% 
  add_header_above(c(" " = 1, "Proportion of Female PhD Recipients by Field" = 3))

phd_prop_tble

```



```{r}

# 3. Male and female salaries for starting postdoctoral and other employment positions (2015).

mf_sal_postdoc_sum <- doc_salary %>% 
  group_by(sex) %>% 
  filter(postgrad_plan == "Postdoctoral study") %>% 
  summarize(
    mean_salary = mean(salary),
    sd_salary = sd(salary),
    sample_size = length(salary),
    datatype = "Postdoctoral Employment"
  )
mf_sal_postdoc_sum

mf_sal_empl_sum <- doc_salary %>% 
  group_by(sex) %>% 
  filter(postgrad_plan == "Employment") %>% 
  summarize(
    mean_salary = mean(salary),
    sd_salary = sd(salary),
    sample_size = length(salary),
    datatype = "Non-Postdoctoral Employment"
  )
mf_sal_empl_sum

# Joining summary tables

mf_sal_sum <- full_join(mf_sal_empl_sum, mf_sal_postdoc_sum) 
mf_sal_sum

# Exploratory Histogram and QQ-plot

mf_sal_hist <-  ggplot(doc_salary, aes(doc_salary$salary)) +
  geom_histogram(aes(fill = sex, bins = 10), position = "dodge")
mf_sal_hist
mf_sal_qq <- ggplot(doc_salary, aes(sample = salary))+
  geom_qq(aes(fill = sex))
mf_sal_qq

# Data appear to be non-normal, n = 15, will use Mann-Whitney U test 


### Summary Column Graph

male_female_sal_graph <- ggplot(mf_sal_sum, aes(x= sex, y = mean_salary/1000)) +
  geom_col(aes(fill = sex), position = "dodge", fill = c("tomato","skyblue","tomato","skyblue"), color = "black") +
  facet_wrap(~datatype) +
  theme_classic() +
  labs(x = "Sex", y = "Average Median Salary ($1000)") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,120)) +
  theme(legend.position = "none") +
  geom_errorbar(aes(ymin=(mean_salary-sd_salary)/1000, ymax=(mean_salary+sd_salary)/1000, width=.15)) 

male_female_sal_graph

### Mann-Whitney U test and Cliff's Delta for both Non-Postdoc and Postdoc ####

# Postdoc

male_sal_postdoc <- doc_salary %>% 
  filter(postgrad_plan == "Postdoctoral study") %>% 
  filter(sex == "Male")
female_sal_postdoc <- doc_salary %>% 
  filter(postgrad_plan == "Postdoctoral study") %>% 
  filter(sex == "Female")
mf_sal_postdoc_mannwhitu <- wilcox.test(male_sal_postdoc$salary,female_sal_postdoc$salary)

mf_sal_postdoc_cliffd <- cliff.delta(male_sal_postdoc$salary,female_sal_postdoc$salary)

mf_sal_postdoc_mannwhitu
mf_sal_postdoc_cliffd # Negligable!

# Non-Postdoc

male_sal_empl <- doc_salary %>% 
  filter(postgrad_plan == "Employment") %>% 
  filter(sex == "Male")
female_sal_empl <- doc_salary %>% 
  filter(postgrad_plan == "Employment") %>% 
  filter(sex == "Female")
mf_sal_empl_mannwhitu <- wilcox.test(male_sal_empl$salary,female_sal_empl$salary)

mf_sal_empl_cliffd <- cliff.delta(male_sal_empl$salary,female_sal_empl$salary)

mf_sal_empl_mannwhitu
mf_sal_empl_cliffd # Small Effect Size



####### What if this is a paired test

mf_sal_postdoc_paired <- wilcox.test(male_sal_postdoc$salary,female_sal_postdoc$salary, paired = TRUE)
mf_sal_postdoc_paired
  
mf_sal_empl_paired <- wilcox.test(male_sal_empl$salary,female_sal_empl$salary, paired = TRUE)
mf_sal_empl_paired


#Paired Graph

doc_salary <- doc_salary %>% 
  mutate(postgrad_plan = ifelse(postgrad_plan == "Employment", "Non-Postdoctoral", "Postdoctoral"))

mf_paired_sal_graph <- ggplot(doc_salary, aes(x= factor(field,levels = rev(levels(factor(field)))), y = salary/1000)) +
  geom_col(aes(fill = sex), position = "dodge") +
  facet_wrap(~postgrad_plan) +
  theme_classic() +
  labs(x = "Field", y = "Median Salary ($1000)") +
  scale_x_discrete(expand = c(0,0),limits = rev(levels(doc_salary$field))) +
  scale_y_continuous(expand = c(0,0)) +
  coord_flip() +
  labs(x = "") +
  theme(panel.spacing = unit(2, "lines")) +
  scale_fill_manual(values=c("tomato","skyblue")) +
  guides(fill=guide_legend(title="Sex"))
  
mf_paired_sal_graph


```

```{r}

# 4. Multiple linear regression

# Visualize salary by sex

by_sex <- ggplot(faculty_salary, aes(x = salary)) +
  geom_density(aes(color = sex, fill = sex), alpha = 0.3) +
  theme_classic() +
  scale_x_continuous(expand = c(0,0), limits = c(0,250000)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Salary", y = "Density")

by_sex

sex_scatter <- ggplot(faculty_salary, aes(x=years_since_phd, y = salary))+
  geom_point(aes(color = sex)) +
  geom_smooth(aes(color = sex), method = lm, se = TRUE, size = 0.5)
sex_scatter

disp_scatter <- ggplot(faculty_salary, aes(x=years_since_phd, y = salary))+
  geom_point(aes(color = discipline)) +
  geom_smooth(aes(color = discipline), method = lm, se = TRUE, size = 0.5)
disp_scatter

```

```{r}
# 4 (cont.)

# Relationship b/w rank and salary

by_rank <- ggplot(faculty_salary, aes(x = faculty_rank, y = salary)) +
  geom_point(aes(color = sex, pch = sex), alpha = 0.5) +
  facet_wrap(~sex)

by_rank

```

```{r}
# 4 (cont.)

# saturated model

# Allison said that there is no example of multiple linear regression. Should discuss the multiple variables and how they affect reference variable. Could use multiple models. 

salary_lm1 <- lm(salary ~ faculty_rank + years_since_phd + years_faculty_service + sex + discipline, data = faculty_salary)

salary_lm1

summary(salary_lm1)


```

```{r}
# 4 (cont.)

# updated model

salary_lm2 <- lm(salary ~ faculty_rank + sex + discipline, data = faculty_salary)

salary_lm2

summary(salary_lm2)

```

```{r}
# 4. (cont.)

# Model diagnostics

plot(salary_lm2)
plot(salary_lm1)

```

```{r}
# 4. (cont.)

# Compare AIC values for each model

lm1_aic <- AIC(salary_lm1)

lm2_aic <- AIC(salary_lm2)

lm1_aic
lm2_aic
```
<<<<<<< HEAD
```{r stargazer, results = 'asis'}
=======
```{r stargazer, results = "asis"}
>>>>>>> 6e2dcb21b519f815ed9fd7eab4af28735e63d6b8

# 4. (cont.)

# Prepare regregression table using stargazer 

stargazer(salary_lm1, salary_lm2, type = "html")

# Explore multicollinearity? cor() and/or pairs()? Data needs to be numeric. Use dummy variables?



```

